jwt:
  access:
    secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    expiration: 86400 # a day
  refresh:
    secret: 52A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    expiration: 604800 # 7 days
---
spring:
  name: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/code_challenge
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:  Ov23liWrF6khpQ0MJ9UM
            clientSecret: fa2e6d6782d52adbdc905ea4beded0abf9678b72
---
spring:
  name: test
  datasource:
    url: jdbc:postgresql://localhost:5432/code_challenge_test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liWrF6khpQ0MJ9UM
            clientSecret: fa2e6d6782d52adbdc905ea4beded0abf9678b72

